### ISSUE TITLE
base_events.py:412: RuntimeWarning: coroutine 'process_events' was never awaited

### ISSUE THREAD

**Issue by Fr6jDJF** [gabdube/python-vulkan-triangle#5]
While trying this triangle example I got the following output 

> 
> Traceback (most recent call last):
>   File "triangle.py", line 1693, in <module>
>     main()
>   File "triangle.py", line 1686, in main
>     app = TriangleApplication()
>   File "triangle.py", line 1626, in __init__
>     Application.__init__(self)
>   File "triangle.py", line 832, in __init__
>     self.create_instance()
>   File "triangle.py", line 291, in create_instance
>     raise RuntimeError('Instance creation failed. Error code: {}'.format(result))
> RuntimeError: Instance creation failed. Error code: 4294967289
> Task was destroyed but it is pending!
> task: <Task pending coro=<process_events() running at /home/..../python-vulkan-triangle-master/xlib.py:277>>
> **/usr/lib/python3.5/asyncio/base_events.py:412: RuntimeWarning: coroutine 'process_events' was never awaited**

Python 3.5 virtualenv
Linux Mint 18.3 Kernel 4.15.0-38 (Ubuntu 16.04)
libvulkan1 1.0.61.1+dfsg1-1ubuntu1~16.04.1

**Comment by Fr6jDJF** [comment]
Example seems to work ok under:
Python 3.6  virtualenv
Linux Mint 19(Ubuntu 18.04)
libvulkan1 1.1.82.0-0ubuntu0.18.04.1**~gpu1**

```
Debug
Function CreateAndroidSurfaceKHR could not be loaded. (__debug__ == True)
Function CreateDisplayPlaneSurfaceKHR could not be loaded. (__debug__ == True)
Function CreateMirSurfaceKHR could not be loaded. (__debug__ == True)
Function CreateWaylandSurfaceKHR could not be loaded. (__debug__ == True)
Function CreateWin32SurfaceKHR could not be loaded. (__debug__ == True)
Function CreateXlibSurfaceKHR could not be loaded. (__debug__ == True)
Function CreateDebugReportCallbackEXT could not be loaded. (__debug__ == True)
Function DestroyDebugReportCallbackEXT could not be loaded. (__debug__ == True)
Function DebugReportMessageEXT could not be loaded. (__debug__ == True)
Function GetPhysicalDeviceDisplayPropertiesKHR could not be loaded. (__debug__ == True)
Function GetPhysicalDeviceDisplayPlanePropertiesKHR could not be loaded. (__debug__ == True)
Function GetDisplayPlaneSupportedDisplaysKHR could not be loaded. (__debug__ == True)
Function GetDisplayModePropertiesKHR could not be loaded. (__debug__ == True)
Function CreateDisplayModeKHR could not be loaded. (__debug__ == True)
Function GetDisplayPlaneCapabilitiesKHR could not be loaded. (__debug__ == True)
Function GetPhysicalDeviceMirPresentationSupportKHR could not be loaded. (__debug__ == True)
Function GetPhysicalDeviceWaylandPresentationSupportKHR could not be loaded. (__debug__ == True)
Function GetPhysicalDeviceWin32PresentationSupportKHR could not be loaded. (__debug__ == True)
Function GetPhysicalDeviceXlibPresentationSupportKHR could not be loaded. (__debug__ == True)
Function CreateSharedSwapchainsKHR could not be loaded. (__debug__ == True)
Running!
Application freed!
```
